//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS.rih419.Practica_03 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_En {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_En() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSS.rih419.Practica_03.Strings-En", typeof(Strings_En).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos;s Turn.
        /// </summary>
        internal static string DesarrolloTurno1 {
            get {
                return ResourceManager.GetString("DesarrolloTurno1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write the number of the column where you want to put your token.
        /// </summary>
        internal static string DesarrolloTurno2 {
            get {
                return ResourceManager.GetString("DesarrolloTurno2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not valid column, please try again.
        /// </summary>
        internal static string DesarrolloTurno3 {
            get {
                return ResourceManager.GetString("DesarrolloTurno3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The token has inert correctly.
        /// </summary>
        internal static string DesarrolloTurno4 {
            get {
                return ResourceManager.GetString("DesarrolloTurno4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Dificulatd10 {
            get {
                return ResourceManager.GetString("Dificulatd10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write the name of the first player.
        /// </summary>
        internal static string Dificultad1 {
            get {
                return ResourceManager.GetString("Dificultad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Dificultad11 {
            get {
                return ResourceManager.GetString("Dificultad11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write the name of the second player.
        /// </summary>
        internal static string Dificultad2 {
            get {
                return ResourceManager.GetString("Dificultad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The token of .
        /// </summary>
        internal static string Dificultad3 {
            get {
                return ResourceManager.GetString("Dificultad3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a is.
        /// </summary>
        internal static string Dificultad4 {
            get {
                return ResourceManager.GetString("Dificultad4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nobody has won.
        /// </summary>
        internal static string Dificultad5 {
            get {
                return ResourceManager.GetString("Dificultad5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a END OF THE GAME.
        /// </summary>
        internal static string Dificultad6 {
            get {
                return ResourceManager.GetString("Dificultad6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The player.
        /// </summary>
        internal static string Dificultad7 {
            get {
                return ResourceManager.GetString("Dificultad7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a is the winner.
        /// </summary>
        internal static string Dificultad8 {
            get {
                return ResourceManager.GetString("Dificultad8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write your name.
        /// </summary>
        internal static string Dificultad9 {
            get {
                return ResourceManager.GetString("Dificultad9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dificulty not valid, please try again:.
        /// </summary>
        internal static string Encabezado {
            get {
                return ResourceManager.GetString("Encabezado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Let start the game.
        /// </summary>
        internal static string Encabezado1 {
            get {
                return ResourceManager.GetString("Encabezado1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Press 1 to Player vs Player.
        /// </summary>
        internal static string Encabezado2 {
            get {
                return ResourceManager.GetString("Encabezado2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Press 2 to Player vs IA level easy.
        /// </summary>
        internal static string Encabezado3 {
            get {
                return ResourceManager.GetString("Encabezado3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Press 3 to Player vs IA level medium.
        /// </summary>
        internal static string Encabezado4 {
            get {
                return ResourceManager.GetString("Encabezado4", resourceCulture);
            }
        }
    }
}
